### ISSUE TITLE
Q: Join two RichTextValues

### ISSUE THREAD

**Issue by oshliaer** [tanaikech/RichTextApp#3]
Is there a method for join two RichTextValues?

**Comment by tanaikech** [comment]
I have to apologize for my late response. Now, I noticed your comment. About joining multiple RichTextValues, is this repository useful? https://github.com/tanaikech/RichTextAssistant

**Comment by oshliaer** [comment]
Thanks!

**Comment by tanaikech** [comment]
Thank you for your reply. I appreciate your always support. It seems that there is a case that the notification email doesn't reach me from GitHub. I would like to try to resolve this.

**Comment by oshliaer** [comment]
I had used the same approach. And now I can use a library. That great!

**Comment by tanaikech** [comment]
Thank you, too!
